### PR TITLE
A bit of cleanup

### PR DESCRIPTION
**Pull request by MrMetric**
Stuff done:
<ul>
<li>deleted trailing whitespace (not for all files)</li>
<li>changed space indentation to tabs (not for all files)</li>
<li>deleted unnecessary semicolons</li>
<li>deleted redundant casts</li>
<li>deleted unused imports</il>
<li>combined some if-blocks (<a href="https://github.com/MrMetric/BigReactors/commit/33dd4640e7f1e45a9dda8a0d779f64efe328c6ff#diff-d40be1bdf8ae1656b34d9f3c53f9b56dL27">link</a>)</li>
<li>deleted redundant checks for >= 0 with byte values</il>
</ul>

Hey, do you have style guidelines anywhere? I've noticed some inconsistent formatting, and I don't know what to change what to.

### CODE REVIEW

**Comment by erogenousbeef** [comment]
While I appreciate the effort, I'm rejecting this. This sort of nonfunctional change will cause merge havoc between the dev and main branches.

**Comment by MrMetric** [comment]
Oh, I didn't notice that (I don't do much with git). Is there some time in the future that formatting changes will be accepted?

Would it be okay if I submit the small code changes only? (the last 2 items in the list)

**Comment by erogenousbeef** [comment]
I'd prefer if you waited until I merged dev-0.5 into master. GDC is eating my brain right now, so I wouldn't expect that to happen until around Easter.

**Comment by MrMetric** [comment]
Alrighty then. I'll put a reminder in my calendar :]

**Pull request closed without merging**
