### PR TITLE
Initial draft of gui localization

### PR DESCRIPTION
**Pull request by Adaptivity**
First try of gui localization. If it gets merged I'll do the rest of localization.

### CODE REVIEW

**Comment by Adaptivity** [comment]
@erogenousbeef gonna look into it?

**Comment by erogenousbeef** [comment]
Yes, will look into it when I have time. Quite a busy week IRL, sorry.

**Comment by Adaptivity** [comment]
Ok. Will wait.

**Comment by Adaptivity** [comment]
lol, Github seems to killed this PR. Closing.

**Pull request closed without merging**
